name: Bug Report
description: Something is not working
title: 'bug: <title>'
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: I have tried the Pre-Release of the extension.
      description: Please try and replicate the Issue in the latest Pre-Release version of the extension.
      options:
        - label: I have replicated the Issue in the latest Pre-Release
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please include steps to reproduce your issue, provide example code snippets if possible
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: Please include screenshots if possible to make it clear and easier to reproduce the issue
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      placeholder: What did you expect to happen instead
    validations:
      required: true
  - type: input
    id: modern-fortran-version
    attributes:
      label: Version of Modern Fortran
      placeholder: v3.0.0, ...
    validations:
      required: true
  - type: input
    id: vscode-version
    attributes:
      label: Version of Visual Studio Code
      placeholder: v1.68.0, ...
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform and Architecture
      placeholder: Linux, MacOS/ARM, Windows, OpenBSD, ...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      placeholder: Further relevant context, i.e. links to other issues
    validations:
      required: false
