name: Feature Request
description: Suggest an idea for this project
title: 'feat: <title>'
labels: [feature-request]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing request for this?
      description: Please search to see if an issue already exists for the feature you are suggesting.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: I have tried the Pre-Release of the extension.
      description: Please try and replicate the Issue in the latest Pre-Release version of the extension.
      options:
        - label: Feature is not present in the latest Pre-Release
          required: true
  - type: textarea
    attributes:
      label: Feature Request
      description: |
        Describe the feature you'd like.
    validations:
      required: true
